import type { Comment } from '../types/comment-types';

export const LATEST_COMMENTS: Comment[] = [
  {
    id: 'c1',
    userId: 'u1',
    username: 'ShadowKing',
    avatarUrl: 'https://placehold.co/40x40/3b82f6/ffffff?text=SK',
    content: 'Chapter 248 was absolutely incredible! The final battle exceeded all expectations.',
    likes: 342,
    dislikes: 12,
    createdAt: '2026-02-11T01:45:00Z',
    mangaId: '1',
    mangaTitle: 'Solo Leveling: Arise',
  },
  {
    id: 'c2',
    userId: 'u2',
    username: 'MangaLove98',
    avatarUrl: 'https://placehold.co/40x40/a855f7/ffffff?text=ML',
    content: 'The art in this chapter is on another level. Oda never disappoints!',
    likes: 256,
    dislikes: 8,
    createdAt: '2026-02-11T00:30:00Z',
    mangaId: '2',
    mangaTitle: 'One Piece',
  },
  {
    id: 'c3',
    userId: 'u3',
    username: 'WebtoonFan',
    avatarUrl: 'https://placehold.co/40x40/22c55e/ffffff?text=WF',
    content: 'Kim Dokja is the best protagonist. This chapter proves it!',
    likes: 189,
    dislikes: 5,
    createdAt: '2026-02-10T23:15:00Z',
    mangaId: '3',
    mangaTitle: 'Omniscient Reader',
  },
  {
    id: 'c4',
    userId: 'u4',
    username: 'ActionHero',
    avatarUrl: 'https://placehold.co/40x40/f59e0b/ffffff?text=AH',
    content: 'Baam keeps getting stronger. Cant wait for the next floor!',
    likes: 145,
    dislikes: 3,
    createdAt: '2026-02-10T21:00:00Z',
    mangaId: '4',
    mangaTitle: 'Tower of God',
  },
  {
    id: 'c5',
    userId: 'u5',
    username: 'FantasyReader',
    avatarUrl: 'https://placehold.co/40x40/ef4444/ffffff?text=FR',
    content: 'Arthur Grey is peak fiction. The world building is insane!',
    likes: 98,
    dislikes: 2,
    createdAt: '2026-02-10T19:45:00Z',
    mangaId: '5',
    mangaTitle: 'The Beginning After The End',
  },
];

// Manga comments with replies (for MangaDetailPage)
export const MANGA_COMMENTS: Record<string, Comment[]> = {
  '1': [
    {
      id: 'mc1',
      userId: 'u1',
      username: 'ShadowKing',
      avatarUrl: 'https://placehold.co/40x40/3b82f6/ffffff?text=SK',
      content: 'This manga is absolutely incredible! The art style is amazing and the story keeps getting better.',
      likes: 42,
      dislikes: 3,
      createdAt: '2026-02-12T10:30:00Z',
      mangaId: '1',
      mangaTitle: 'Solo Leveling: Arise',
      replyCount: 2,
      replies: [
        {
          id: 'mc1-r1',
          userId: 'u2',
          username: 'MangaLove98',
          avatarUrl: 'https://placehold.co/40x40/a855f7/ffffff?text=ML',
          content: 'Totally agree! The character development is top-notch too.',
          likes: 15,
          dislikes: 1,
          createdAt: '2026-02-12T11:00:00Z',
          mangaId: '1',
          mangaTitle: 'Solo Leveling: Arise',
          parentId: 'mc1',
          replies: [
            {
              id: 'mc1-r1-r1',
              userId: 'u1',
              username: 'ShadowKing',
              avatarUrl: 'https://placehold.co/40x40/3b82f6/ffffff?text=SK',
              content: 'Right? The plot twists are insane!',
              likes: 8,
              dislikes: 0,
              createdAt: '2026-02-12T11:15:00Z',
              mangaId: '1',
              mangaTitle: 'Solo Leveling: Arise',
              parentId: 'mc1-r1',
            },
          ],
        },
      ],
    },
    {
      id: 'mc2',
      userId: 'u3',
      username: 'WebtoonFan',
      avatarUrl: 'https://placehold.co/40x40/22c55e/ffffff?text=WF',
      content: 'Just binged all 50 chapters. The world-building is phenomenal!',
      likes: 28,
      dislikes: 2,
      createdAt: '2026-02-12T08:00:00Z',
      mangaId: '1',
      mangaTitle: 'Solo Leveling: Arise',
    },
  ],
};

// Chapter comments (for ReaderPage sidebar)
export const CHAPTER_COMMENTS: Record<string, Comment[]> = {
  'ch-1-42': [
    {
      id: 'cc1',
      userId: 'u1',
      username: 'ShadowKing',
      avatarUrl: 'https://placehold.co/40x40/3b82f6/ffffff?text=SK',
      content: 'This chapter is fire! 🔥',
      likes: 12,
      dislikes: 1,
      createdAt: '2026-02-12T15:00:00Z',
      mangaId: '1',
      mangaTitle: 'Solo Leveling: Arise',
      chapterId: 'ch-1-42',
    },
    {
      id: 'cc2',
      userId: 'u3',
      username: 'WebtoonFan',
      avatarUrl: 'https://placehold.co/40x40/22c55e/ffffff?text=WF',
      content: 'The plot twist on page 15 was unexpected!',
      likes: 8,
      dislikes: 0,
      createdAt: '2026-02-12T14:30:00Z',
      mangaId: '1',
      mangaTitle: 'Solo Leveling: Arise',
      chapterId: 'ch-1-42',
    },
    {
      id: 'cc3',
      userId: 'u2',
      username: 'MangaLove98',
      avatarUrl: 'https://placehold.co/40x40/a855f7/ffffff?text=ML',
      content: 'Finally caught up! Worth the wait 💯',
      likes: 5,
      dislikes: 0,
      createdAt: '2026-02-12T14:00:00Z',
      mangaId: '1',
      mangaTitle: 'Solo Leveling: Arise',
      chapterId: 'ch-1-42',
    },
  ],
};

// Page comments (for PageCommentModal)
export const PAGE_COMMENTS: Record<string, Comment[]> = {
  'ch-1-42-p15': [
    {
      id: 'pc1',
      userId: 'u1',
      username: 'ShadowKing',
      avatarUrl: 'https://placehold.co/40x40/3b82f6/ffffff?text=SK',
      content: 'This panel is beautifully drawn! The detail on the shadows is insane 🔥',
      likes: 24,
      dislikes: 2,
      createdAt: '2026-02-12T15:30:00Z',
      mangaId: '1',
      mangaTitle: 'Solo Leveling: Arise',
      chapterId: 'ch-1-42',
      pageNumber: 15,
    },
    {
      id: 'pc2',
      userId: 'u2',
      username: 'MangaLove98',
      avatarUrl: 'https://placehold.co/40x40/a855f7/ffffff?text=ML',
      content: "The protagonist's expression here is so intense!",
      likes: 8,
      dislikes: 0,
      createdAt: '2026-02-12T15:15:00Z',
      mangaId: '1',
      mangaTitle: 'Solo Leveling: Arise',
      chapterId: 'ch-1-42',
      pageNumber: 15,
    },
  ],
};
