import type { Manga, MangaRanked } from '../types/manga-types';

export const FEATURED_MANGA: Manga[] = [
  {
    id: '1',
    title: 'Solo Leveling: Arise',
    slug: 'solo-leveling-arise',
    coverUrl: 'https://placehold.co/300x450/1a1e2e/3b82f6?text=Solo+Leveling',
    author: 'Chugong',
    genres: ['Action', 'Fantasy'],
    latestChapter: 248,
    totalChapters: 248,
    views: 2400000,
    updatedAt: '2026-02-10T10:00:00Z',
    status: 'completed',
    badge: 'hot',
  },
  {
    id: '2',
    title: 'One Piece',
    slug: 'one-piece',
    coverUrl: 'https://placehold.co/300x450/1a1e2e/a855f7?text=One+Piece',
    author: 'Eiichiro Oda',
    genres: ['Adventure', 'Action'],
    latestChapter: 1120,
    totalChapters: 1120,
    views: 5800000,
    updatedAt: '2026-02-09T08:00:00Z',
    status: 'ongoing',
    badge: 'top',
  },
  {
    id: '3',
    title: 'Omniscient Reader',
    slug: 'omniscient-reader',
    coverUrl: 'https://placehold.co/300x450/1a1e2e/22c55e?text=Omniscient+Reader',
    author: 'Sing Shong',
    genres: ['Action', 'Fantasy'],
    latestChapter: 195,
    totalChapters: 195,
    views: 1800000,
    updatedAt: '2026-02-10T12:00:00Z',
    status: 'ongoing',
    badge: 'new',
  },
  {
    id: '4',
    title: 'Tower of God',
    slug: 'tower-of-god',
    coverUrl: 'https://placehold.co/300x450/1a1e2e/f59e0b?text=Tower+of+God',
    author: 'SIU',
    genres: ['Action', 'Adventure'],
    latestChapter: 610,
    totalChapters: 610,
    views: 3200000,
    updatedAt: '2026-02-08T14:00:00Z',
    status: 'ongoing',
  },
  {
    id: '5',
    title: 'The Beginning After The End',
    slug: 'beginning-after-the-end',
    coverUrl: 'https://placehold.co/300x450/1a1e2e/ef4444?text=TBATE',
    author: 'TurtleMe',
    genres: ['Fantasy', 'Action'],
    latestChapter: 205,
    totalChapters: 205,
    views: 2100000,
    updatedAt: '2026-02-10T06:00:00Z',
    status: 'ongoing',
    badge: 'hot',
  },
  {
    id: '6',
    title: 'Eleceed',
    slug: 'eleceed',
    coverUrl: 'https://placehold.co/300x450/1a1e2e/3b82f6?text=Eleceed',
    author: 'Son Jae Ho',
    genres: ['Action', 'Comedy'],
    latestChapter: 312,
    totalChapters: 312,
    views: 1500000,
    updatedAt: '2026-02-09T16:00:00Z',
    status: 'ongoing',
  },
];

export const LATEST_MANGA: Manga[] = [
  {
    id: '7',
    title: 'The Ancient Ones Legacy',
    slug: 'ancient-ones-legacy',
    coverUrl: 'https://placehold.co/120x160/1a1e2e/3b82f6?text=Ancient',
    author: 'Kim Eun-jung',
    genres: ['Action', 'Adventure'],
    latestChapter: 89,
    totalChapters: 89,
    views: 450000,
    updatedAt: '2026-02-11T02:00:00Z',
    status: 'ongoing',
  },
  {
    id: '8',
    title: "Omniscient Reader's Viewpoint",
    slug: 'omniscient-readers-viewpoint',
    coverUrl: 'https://placehold.co/120x160/1a1e2e/a855f7?text=ORV',
    author: 'Sing Shong',
    genres: ['Action', 'Fantasy'],
    latestChapter: 195,
    totalChapters: 195,
    views: 1800000,
    updatedAt: '2026-02-11T01:30:00Z',
    status: 'ongoing',
    badge: 'hot',
  },
  {
    id: '9',
    title: 'Berserk',
    slug: 'berserk',
    coverUrl: 'https://placehold.co/120x160/1a1e2e/ef4444?text=Berserk',
    author: 'Kentaro Miura',
    genres: ['Action', 'Drama'],
    latestChapter: 375,
    totalChapters: 375,
    views: 2900000,
    updatedAt: '2026-02-10T22:00:00Z',
    status: 'hiatus',
  },
  {
    id: '10',
    title: 'Kingdom',
    slug: 'kingdom',
    coverUrl: 'https://placehold.co/120x160/1a1e2e/22c55e?text=Kingdom',
    author: 'Yasuhisa Hara',
    genres: ['Action', 'Historical'],
    latestChapter: 798,
    totalChapters: 798,
    views: 1600000,
    updatedAt: '2026-02-10T20:00:00Z',
    status: 'ongoing',
  },
  {
    id: '11',
    title: 'Chainsaw Man',
    slug: 'chainsaw-man',
    coverUrl: 'https://placehold.co/120x160/1a1e2e/f59e0b?text=CSM',
    author: 'Tatsuki Fujimoto',
    genres: ['Action', 'Horror'],
    latestChapter: 185,
    totalChapters: 185,
    views: 2200000,
    updatedAt: '2026-02-10T18:00:00Z',
    status: 'ongoing',
    badge: 'hot',
  },
];

export const TOP_MANGA_DAILY: MangaRanked[] = [
  { ...FEATURED_MANGA[0], rank: 1, viewsFormatted: '2.4M Views' },
  { ...FEATURED_MANGA[2], rank: 2, viewsFormatted: '1.8M Views' },
  { ...FEATURED_MANGA[4], rank: 3, viewsFormatted: '2.1M Views' },
];

export const TOP_MANGA_WEEKLY: MangaRanked[] = [
  { ...FEATURED_MANGA[1], rank: 1, viewsFormatted: '5.8M Views' },
  { ...FEATURED_MANGA[3], rank: 2, viewsFormatted: '3.2M Views' },
  { ...FEATURED_MANGA[0], rank: 3, viewsFormatted: '2.4M Views' },
];

export const TOP_MANGA_MONTHLY: MangaRanked[] = [
  { ...FEATURED_MANGA[1], rank: 1, viewsFormatted: '12.5M Views' },
  { ...FEATURED_MANGA[0], rank: 2, viewsFormatted: '8.2M Views' },
  { ...FEATURED_MANGA[3], rank: 3, viewsFormatted: '6.8M Views' },
];
