import type { Comment } from '../types/comment-types';

export const LATEST_COMMENTS: Comment[] = [
  {
    id: 'c1',
    userId: 'u1',
    username: 'ShadowKing',
    avatarUrl: 'https://placehold.co/40x40/3b82f6/ffffff?text=SK',
    content: 'Chapter 248 was absolutely incredible! The final battle exceeded all expectations.',
    likes: 342,
    createdAt: '2026-02-11T01:45:00Z',
    mangaId: '1',
    mangaTitle: 'Solo Leveling: Arise',
  },
  {
    id: 'c2',
    userId: 'u2',
    username: 'MangaLove98',
    avatarUrl: 'https://placehold.co/40x40/a855f7/ffffff?text=ML',
    content: 'The art in this chapter is on another level. Oda never disappoints!',
    likes: 256,
    createdAt: '2026-02-11T00:30:00Z',
    mangaId: '2',
    mangaTitle: 'One Piece',
  },
  {
    id: 'c3',
    userId: 'u3',
    username: 'WebtoonFan',
    avatarUrl: 'https://placehold.co/40x40/22c55e/ffffff?text=WF',
    content: 'Kim Dokja is the best protagonist. This chapter proves it!',
    likes: 189,
    createdAt: '2026-02-10T23:15:00Z',
    mangaId: '3',
    mangaTitle: 'Omniscient Reader',
  },
  {
    id: 'c4',
    userId: 'u4',
    username: 'ActionHero',
    avatarUrl: 'https://placehold.co/40x40/f59e0b/ffffff?text=AH',
    content: 'Baam keeps getting stronger. Cant wait for the next floor!',
    likes: 145,
    createdAt: '2026-02-10T21:00:00Z',
    mangaId: '4',
    mangaTitle: 'Tower of God',
  },
  {
    id: 'c5',
    userId: 'u5',
    username: 'FantasyReader',
    avatarUrl: 'https://placehold.co/40x40/ef4444/ffffff?text=FR',
    content: 'Arthur Grey is peak fiction. The world building is insane!',
    likes: 98,
    createdAt: '2026-02-10T19:45:00Z',
    mangaId: '5',
    mangaTitle: 'The Beginning After The End',
  },
];
